version: '3.9'

services:
  web:
    command: python3 manage.py runserver 0.0.0.0:80
    image: nirutg/lcps_v1:deploy4.0
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 8000:80
    environment:
      - HOST=0.0.0.0
      - PORT=80
    
    